name: Terraform Build

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Confirm Apply"
        required: true
        default: "yes"

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: eks-terraform

      - name: Terraform Apply
        if: ${{ github.event.inputs.confirm == 'yes' }}
        run: terraform apply -auto-approve
        working-directory: eks-terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
